from .test_calc2 import TestCalc2
from .test_calc4 import TestCalc4
from .test_calc5 import TestCalc5
from .test_calc6 import TestCalc6
from .test_calc7 import TestCalc7
from .test_calc8 import TestCalc8
from .test_calc9 import TestCalc9
from .test_calc10 import TestCalc10
from .test_calc11 import TestCalc11
from .test_calc12 import TestCalc12
from .test_calc15 import TestCalc15
from .test_calc16 import TestCalc16
from .test_calc17 import TestCalc17
from .test_calc18 import TestCalc18
